/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * backend
 * SmartAgenda Backend - Express API Server
 * OpenAPI spec version: 1.0.0
 */
export interface AppSettingsResponse {
  pageTitle: string
}

export interface UpdateAppSettingsRequest {
  pageTitle?: string
}

export type AppointmentStatus = (typeof AppointmentStatus)[keyof typeof AppointmentStatus]

export const AppointmentStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled',
} as const

export interface Appointment {
  id: string
  customerName: string
  customerPhone: string
  service: string
  date: string
  duration: number
  status: AppointmentStatus
  price: number
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
export interface PickAppointmentExcludeKeyofAppointmentIdOrStatus {
  customerName: string
  customerPhone: string
  service: string
  date: string
  duration: number
  price: number
}

/**
 * Construct a type with the properties of T except for those in type K.
 */
export type OmitAppointmentIdOrStatus = PickAppointmentExcludeKeyofAppointmentIdOrStatus

export type AppointmentCreationParams = PickAppointmentExcludeKeyofAppointmentIdOrStatus

export type getSettingsResponse200 = {
  data: AppSettingsResponse
  status: 200
}

export type getSettingsResponseSuccess = getSettingsResponse200 & {
  headers: Headers
}
export type getSettingsResponse = getSettingsResponseSuccess

export const getGetSettingsUrl = () => {
  return `http://localhost:4100/settings`
}

export const getSettings = async (options?: RequestInit): Promise<getSettingsResponse> => {
  const res = await fetch(getGetSettingsUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getSettingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSettingsResponse
}

export type updateSettingsResponse200 = {
  data: AppSettingsResponse
  status: 200
}

export type updateSettingsResponseSuccess = updateSettingsResponse200 & {
  headers: Headers
}
export type updateSettingsResponse = updateSettingsResponseSuccess

export const getUpdateSettingsUrl = () => {
  return `http://localhost:4100/settings`
}

export const updateSettings = async (
  updateAppSettingsRequest: UpdateAppSettingsRequest,
  options?: RequestInit
): Promise<updateSettingsResponse> => {
  const res = await fetch(getUpdateSettingsUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAppSettingsRequest),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: updateSettingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateSettingsResponse
}

export type getAppointmentsResponse200 = {
  data: Appointment[]
  status: 200
}

export type getAppointmentsResponseSuccess = getAppointmentsResponse200 & {
  headers: Headers
}
export type getAppointmentsResponse = getAppointmentsResponseSuccess

export const getGetAppointmentsUrl = () => {
  return `http://localhost:4100/appointments`
}

export const getAppointments = async (options?: RequestInit): Promise<getAppointmentsResponse> => {
  const res = await fetch(getGetAppointmentsUrl(), {
    ...options,
    method: 'GET',
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getAppointmentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAppointmentsResponse
}

export type createAppointmentResponse201 = {
  data: Appointment
  status: 201
}

export type createAppointmentResponseSuccess = createAppointmentResponse201 & {
  headers: Headers
}
export type createAppointmentResponse = createAppointmentResponseSuccess

export const getCreateAppointmentUrl = () => {
  return `http://localhost:4100/appointments`
}

export const createAppointment = async (
  pickAppointmentExcludeKeyofAppointmentIdOrStatus: PickAppointmentExcludeKeyofAppointmentIdOrStatus,
  options?: RequestInit
): Promise<createAppointmentResponse> => {
  const res = await fetch(getCreateAppointmentUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(pickAppointmentExcludeKeyofAppointmentIdOrStatus),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: createAppointmentResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createAppointmentResponse
}
